workflows:
  workflows/release.yml:
    jobs:
      build_docs:
        strategy:
          matrix:
            xcode: latest

  workflows/push.yml:
    jobs:
      swiftpm_tests:
        strategy:
          matrix:
            xcode:
              - last-major
              - latest
              - latest-beta
