name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_docs:
    name: Build Docs (Xcode ${{ matrix.xcode }})
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:

          - '12.4'
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - uses: actions/cache@v2.1.7
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build docs
        run: bundle exec jazzy

      - name: Upload Docs
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs

  upload_docs:
    needs: [build_docs]
    name: Upload Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Download Docs
        uses: actions/download-artifact@v2.1.0
        with:
          name: docs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
