name: Tests

on:
  push:
  pull_request:
    branches:
      - "**:**" # PRs from forks have a prefix with `owner:`

jobs:
  swiftpm_tests:
    name: SwiftPM on Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - "12.5.1"
          - "13.2.1"
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: SwiftPM tests
        run: swift test --enable-code-coverage

      - name: Convert coverage to lcov
        run: xcrun llvm-cov export -format="lcov" .build/debug/HashableByKeyPathPackageTests.xctest/Contents/MacOS/HashableByKeyPathPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

  linux_tests:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container:
      image: swift:${{ matrix.swift }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        swift: ["5.2", "5.3"]

    steps:
      - uses: actions/checkout@v2.4.0

      - name: swift test
        run: swift test --enable-test-discovery

  check-gyb-run:
    name: Check GYB has been run
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Install GYB
        run: brew install nshipster/formulae/gyb

      - run: ./scripts/generate-from-gyb.sh

      - name: Check GYB was run before commit
        run: git diff --exit-code
