name: Tests

on:
  push:
    branches: [$default-branch]
  pull_request:

jobs:
  swiftpm_tests:
    name: SwiftPM on Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ["11.4"]

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: SwiftPM tests
        run: swift test --enable-code-coverage

      - name: Convert coverage to lcov
        run: xcrun llvm-cov export -format="lcov" .build/debug/HashableByKeyPathPackageTests.xctest/Contents/MacOS/HashableByKeyPathPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  linux_tests:
    name: SwiftPM on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-latest]
        swift: ["5.2.3"]

    steps:
      - uses: actions/checkout@v2

      - name: Install swiftenv
        run: |
          eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
          echo "SWIFTENV_ROOT=$HOME/.swiftenv" >> $GITHUB_ENV
          echo "$SWIFTENV_ROOT/bin" >> $GITHUB_PATH

      - name: Install Swift ${{ matrix.swift }}
        run: swiftenv install ${{ matrix.swift }}

      - name: swift test
        run: swift test --enable-test-discovery
