name: Tests

on:
  push:
  pull_request:
    branches:
      - "**:**" # PRs from forks have a prefix with `owner:`

jobs:
  swiftpm_tests:
    name: ${{ matrix.platform }} Tests with Swift ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        swift:
          - ~5.2
          - ~5.3
          - ~5.4
          - ~5.5
        platform:
          - macOS
          - watchOS
          - tvOS
          - iOS
        os:
          - macos-11
        include:
          - swift: ~5.2
            os: macos-10.15
          - swift: ~5.3
            os: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - uses: mxcl/xcodebuild@v1
        with:
          swift: ${{ matrix.swift }}
          platform: ${{ matrix.platform }}
          code-coverage: true

      - name: Convert coverage to lcov
        run: xcrun llvm-cov export -format="lcov" .build/debug/HashableByKeyPathPackageTests.xctest/Contents/MacOS/HashableByKeyPathPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  linux_tests:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container:
      image: swift:${{ matrix.swift }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        swift: ["5.2", "5.3", "5.4"]

    steps:
      - uses: actions/checkout@v1

      - name: swift test
        run: swift test --enable-test-discovery

  check-gyb-run:
    name: Check GYB has been run
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install GYB
        run: brew install nshipster/formulae/gyb

      - run: ./scripts/generate-from-gyb.sh

      - name: Check GYB was run before commit
        run: git diff --exit-code
